force-app/main/default/objects/Answered_Question__c/Answered_Question__c.object-meta.xml
<CustomObject>
    <label>Answered Question</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Exam Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answered Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Examforce/objects/Answered_Question__c/fields/Answered_Correctly__c.field-meta.xml
<CustomField>
    <fullName>Answered_Correctly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Answered Correctly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answered_Question__c/fields/Assigned_Exam__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Exam__c</fullName>
    <label>Assigned Exam</label>
    <referenceTo>Assigned_Exam__c</referenceTo>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Examforce/objects/Answered_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answered_Question__c/fields/User_Answer__c.field-meta.xml
<CustomField>
    <fullName>User_Answer__c</fullName>
    <label>User Answer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assigned_Exam__c/Assigned_Exam__c.object-meta.xml
<CustomObject>
    <label>Assigned Exam</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assigned Exam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Answer__c/User_Answer__c.object-meta.xml
<CustomObject>
    <label>User Answer</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>User Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Answer__c/fields/Assigned_Exam__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Exam__c</fullName>
    <label>Assigned Exam</label>
    <referenceTo>Assigned_Exam__c</referenceTo>
    <relationshipLabel>User Answer</relationshipLabel>
    <relationshipName>User_Answer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>User Answer</relationshipLabel>
    <relationshipName>User_Answer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/answeredQCreator.cls
public without sharing class  answeredQCreator {
    @AuraEnabled
        public static void AnsweredQCreator(String s) {
        List<Answered_Question__c> Questions =  (List<Answered_Question__c>) JSON.deserialize(s, List<Answered_Question__c>.class);
        //Answered_Question__c a = new Answered_Question__c(Assigned_Exam__c ='a018Z00000rcR5FQAU',Question__c='a048Z00000jHupAQAS', Answered_Correctly__c = True, User_Answer__c = 'C');
        insert Questions;
        return;
    }
}