force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Examforce/objects/Question__c/fields/Answer_A__c.field-meta.xml
<CustomField>
    <fullName>Answer_A__c</fullName>
    <label>Answer A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Examforce/objects/Question__c/fields/Answer_B__c.field-meta.xml
<CustomField>
    <fullName>Answer_B__c</fullName>
    <label>Answer B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Answer_C__c.field-meta.xml
<CustomField>
    <fullName>Answer_C__c</fullName>
    <label>Answer C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Examforce/objects/Question__c/fields/Answer_D__c.field-meta.xml
<CustomField>
    <fullName>Answer_D__c</fullName>
    <label>Answer D</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Examforce/objects/Question__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Examforce/objects/Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Another Placeholder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Pool__c/Question_Pool__c.object-meta.xml
<CustomObject>
    <label>Question Pool</label>
    <nameField>
        <displayFormat>QP-{0000}</displayFormat>
        <label>Question Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Examforce/objects/Question_Pool__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Question Pools</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Pool__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Pools</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/retrieveExam.cls
public without sharing class retrieveExam {
    @AuraEnabled(cacheable=true)
    public static List<Question_Pool__c> getExam(String q){
        try {
            //String examId = q;
            return [SELECT Question__r.Id, Question__r.Name, Question__r.Body__c, Question__r.Answer_A__c, Question__r.Answer_B__c, Question__r.Answer_C__c, Question__r.Answer_D__c, Question__r.Correct_Answer__c, Question__r.Type__c FROM Question_Pool__c WHERE Exam__r.ID =: q];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}