force-app/main/default/objects/Assigned_Exam__c/Assigned_Exam__c.object-meta.xml
<CustomObject>
    <label>Assigned Exam</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assigned Exam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Exam__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Assigned Exams</relationshipLabel>
    <relationshipName>Assigned_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/examDuration.cls
public class examDuration {
    @AuraEnabled(cacheable=true)
    public static List<Assigned_Exam__c> examDuration(){
        try { //WHERE Name will be a variable that links the users assigned exam

           return [SELECT Exam__r.Duration__c,Exam__r.Name FROM Assigned_Exam__c WHERE Id = 'a018Z00000raxd9QAA'];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}