force-app/main/default/objects/Assigned_Exam__c/Assigned_Exam__c.object-meta.xml
<CustomObject>
    <label>Assigned Exam</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Assigned Exam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Exam__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assigned Exam</relationshipLabel>
    <relationshipName>Assigned_Exam</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigned_Exam__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Assigned Exams</relationshipLabel>
    <relationshipName>Assigned_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/userHelper.cls
public without sharing class userHelper {

    // Need @AuraEnabled to use Apex in Aura or LWC
    // Need public static as well
    // Cacheable stores data in the client side storage so they don't have to wait for a server call
    // cacheable will improve performance, can't use it if you are modifying data
    // Biggest use case is when you are just returning data
    
    @AuraEnabled (cacheable=true)
    public static List<Assigned_Exam__c> getUserName() {
        try {
            String userEmail = UserInfo.getUserEmail();
            Contact con = [SELECT Id FROM Contact WHERE Email =: userEmail];
            return [SELECT Exam__r.Name, Exam__r.Duration__c, Exam__r.id FROM Assigned_Exam__c WHERE Assigned_Exam__c.contact__r.Id =: con.Id];
            //return [SELECT Exam__r.Name, Exam__r.Duration__c, Exam__r.id FROM Assigned_Exam__c WHERE Assigned_Exam__c.contact__r.Id = '0038Z00002sWpZKQA0'];
            //System.debug(userExam);
            //return userExam[0].Exam__r.Name;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        

    }  
    

    

    // @AuraEnabled (cacheable=true)
    // public static string getExam(){
    //     return UserInfo.getUserEmail();
        
    //     //console.log(userId);
        
        
    // }
    
           
  
    
}